FROM node:lts-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Comment the Copy because we mapping the current directory at docker-compose.yml so don need it except we need to run it on production
# COPY . .

CMD [ "npm", "run", "start" ]
